# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 19:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(help_text='To generate the map for your location', srid=4326)),
                ('city_hall', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(100)], verbose_name='edad')),
                ('genero', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], default='M', max_length=1, verbose_name='sexo')),
                ('modo', models.CharField(choices=[('VE', 'Vehiculo particular'), ('BU', 'Bus'), ('MO', 'Moto'), ('BI', 'Bicicleta'), ('CA', 'Caminando')], default='VE', max_length=2, verbose_name='Modo de transporte')),
                ('tiempo_trayecto', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(240)], verbose_name='tiempo aprox. trayecto (minutos)')),
                ('gasto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='gasto mensual en transporte')),
                ('desde', django.contrib.gis.db.models.fields.PointField(help_text='De donde sales', srid=4326, verbose_name='Ubicación de salida')),
                ('hasta', django.contrib.gis.db.models.fields.PointField(help_text='A donde llegas', srid=4326, verbose_name='Ubicación de entrada')),
                ('t_entrada_lunes', models.IntegerField(blank=True, null=True, verbose_name='Hora de entrada - Lunes')),
                ('t_salida_lunes', models.IntegerField(blank=True, null=True, verbose_name='Hora de salida - Lunes')),
                ('t_entrada_martes', models.IntegerField(blank=True, null=True, verbose_name='Hora de entrada - Martes (opcional)')),
                ('t_salida_martes', models.IntegerField(blank=True, null=True, verbose_name='Hora de salida - Martes (opcional)')),
                ('t_entrada_miercoles', models.IntegerField(blank=True, null=True, verbose_name='Hora de entrada - Miércoles (opcional)')),
                ('t_salida_miercoles', models.IntegerField(blank=True, null=True, verbose_name='Hora de salida - Miércoles (opcional)')),
                ('t_entrada_jueves', models.IntegerField(blank=True, null=True, verbose_name='Hora de entrada - Jueves (opcional)')),
                ('t_salida_jueves', models.IntegerField(blank=True, null=True, verbose_name='Hora de salida - Jueves (opcional)')),
                ('t_entrada_viernes', models.IntegerField(blank=True, null=True, verbose_name='Hora de entrada - Viernes (opcional)')),
                ('t_salida_viernes', models.IntegerField(blank=True, null=True, verbose_name='Hora de salida - Viernes (opcional)')),
                ('preferencia_1', models.CharField(choices=[('BU', 'Bus - $2100, 50min'), ('OM', 'Omibus - $3000, 35min'), ('PA', 'Automovil particular - $5000, 30min')], default='BU', max_length=2, verbose_name='¿Con cual de las siguientes opciones te sientes mas comod@? Valores típicos de un trayecto al centro')),
                ('preferencia_2', models.CharField(choices=[('BU', 'Bus - $2100, 50min'), ('OM', 'Omibus - $3500, 30min'), ('PA', 'Automovil particular - $5000, 30min')], default='BU', max_length=2, verbose_name='¿Con cual de las siguientes opciones te sientes mas comod@?')),
                ('preferencia_3', models.CharField(choices=[('BU', 'Bus - $2100, 50min'), ('OM', 'Omibus - $4000, 25min'), ('PA', 'Automovil particular - $5000, 30min')], default='BU', max_length=2, verbose_name='¿Con cual de las siguientes opciones te sientes mas comod@?')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email (opcional)')),
                ('sugerencias', models.TextField(blank=True, verbose_name='sugerencias (opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigment', models.FileField(upload_to='assigments/')),
            ],
        ),
    ]
