# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 19:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='lugar_entrada_lunes',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='lugar_salida',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='desde',
            field=django.contrib.gis.db.models.fields.PointField(default=1, help_text='De donde sales', srid=4326, verbose_name='Ubicación de salida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='hasta',
            field=django.contrib.gis.db.models.fields.PointField(default=1, help_text='A donde llegas', srid=4326, verbose_name='Ubicación de entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='modo',
            field=models.CharField(choices=[('VE', 'Vehiculo particular'), ('BU', 'Bus'), ('MO', 'Moto'), ('BI', 'Bicicleta'), ('CA', 'Caminando')], default='VE', max_length=2, verbose_name='Modo de transporte'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='t_entrada_jueves',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Jueves (opcional)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='t_entrada_martes',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Martes (opcional)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='t_entrada_miercoles',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Miércoles (opcional)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='t_entrada_viernes',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Viernes (opcional)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='t_salida_jueves',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Jueves (opcional)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='t_salida_martes',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Martes (opcional)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='t_salida_miercoles',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Miércoles (opcional)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='t_salida_viernes',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Viernes (opcional)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email (opcional)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(100)], verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='gasto',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='gasto mensual en transporte'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='preferencia',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='¿Utilizarias este producto?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='sugerencias',
            field=models.TextField(blank=True, verbose_name='sugerencias (opcional)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='t_entrada_lunes',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Lunes (opcional)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='t_salida_lunes',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Hora de entrada - Lunes (opcional)'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tiempo_trayecto',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(240)], verbose_name='tiempo aprox. trayecto (minutos)'),
        ),
    ]
